apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs-dynamic
spec:
  storageClassName: nfs-csi-default
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
