apiVersion: v1
entries:
  csi-driver-nfs:
  - apiVersion: v1
    appVersion: v4.8.0
    created: "2024-07-18T07:10:05.767275265Z"
    description: CSI NFS Driver for Kubernetes
    digest: 9e7365d0d6d3f09901d46d753a4d2ad91ebeae36803b5c470b737c0a87e40ddb
    name: csi-driver-nfs
    urls:
    - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts/v4.8.0/csi-driver-nfs-v4.8.0.tgz
    version: v4.8.0
  - apiVersion: v1
    appVersion: v4.7.0
    created: "2024-07-18T07:10:05.766534539Z"
    description: CSI NFS Driver for Kubernetes
    digest: 1a51c5d4f3a8f75ff9d49605a960a7974f5a7accb1bb18dd21b52f3bd54cdb18
    name: csi-driver-nfs
    urls:
    - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts/v4.7.0/csi-driver-nfs-v4.7.0.tgz
    version: v4.7.0
  - apiVersion: v1
    appVersion: v4.6.0
    created: "2024-07-18T07:10:05.765793919Z"
    description: CSI NFS Driver for Kubernetes
    digest: 87db7b8fcf570cb2dc03fb99a240aa602ae042839f9afaf3f3dcab45ac5bf1fc
    name: csi-driver-nfs
    urls:
    - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts/v4.6.0/csi-driver-nfs-v4.6.0.tgz
    version: v4.6.0
  - apiVersion: v1
    appVersion: v4.5.0
    created: "2024-07-18T07:10:05.765004942Z"
    description: CSI NFS Driver for Kubernetes
    digest: 88859da0add70d12f5f42491a7476c06571e98c812812554890f886c93c2ccdf
    name: csi-driver-nfs
    urls:
    - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts/v4.5.0/csi-driver-nfs-v4.5.0.tgz
    version: v4.5.0
  - apiVersion: v1
    appVersion: v4.4.0
    created: "2024-07-18T07:10:05.763699536Z"
    description: CSI NFS Driver for Kubernetes
    digest: 0622c3175268ca4ee38d16d94d6d7d475e5099dde38e2dcbeb3c69e978a4371b
    name: csi-driver-nfs
    urls:
    - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts/v4.4.0/csi-driver-nfs-v4.4.0.tgz
    version: v4.4.0
  - apiVersion: v1
    appVersion: v4.3.0
    created: "2024-07-18T07:10:05.762713485Z"
    description: CSI NFS Driver for Kubernetes
    digest: 36b65d799c79e1b46936828fee7518e2540a62ea532f8a4abf754dd3432d30c9
    name: csi-driver-nfs
    urls:
    - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts/v4.3.0/csi-driver-nfs-v4.3.0.tgz
    version: v4.3.0
  - apiVersion: v1
    appVersion: v4.2.0
    created: "2024-07-18T07:10:05.7620348Z"
    description: CSI NFS Driver for Kubernetes
    digest: e702f6c9be35f2649f5736ca5fcdc40ab1c6a235f41e7fb2472d208e8a5ebf47
    name: csi-driver-nfs
    urls:
    - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts/v4.2.0/csi-driver-nfs-v4.2.0.tgz
    version: v4.2.0
  - apiVersion: v1
    appVersion: v4.1.0
    created: "2024-07-18T07:10:05.76159226Z"
    description: CSI NFS Driver for Kubernetes
    digest: b2baa2f129976cf2981c8873290aac509aa3c5937ffc319fbf69fbe3271c23eb
    name: csi-driver-nfs
    urls:
    - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts/v4.1.0/csi-driver-nfs-v4.1.0.tgz
    version: v4.1.0
  - apiVersion: v1
    appVersion: v4.0.0
    created: "2024-07-18T07:10:05.761152356Z"
    description: CSI NFS Driver for Kubernetes
    digest: 3145fd12225a639908b14675c8ae1f272bc0e57ffa2895b6f17411486a24229d
    name: csi-driver-nfs
    urls:
    - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts/v4.0.0/csi-driver-nfs-v4.0.0.tgz
    version: v4.0.0
  - apiVersion: v1
    appVersion: v3.1.0
    created: "2024-07-18T07:10:05.760688174Z"
    description: CSI NFS Driver for Kubernetes
    digest: 7e51bb9188b013195cafc265102fa365de9ec5513780e1dfc5363289f811a4d9
    name: csi-driver-nfs
    urls:
    - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts/v3.1.0/csi-driver-nfs-v3.1.0.tgz
    version: v3.1.0
  - apiVersion: v1
    appVersion: v3.0.0
    created: "2024-07-18T07:10:05.760264006Z"
    description: CSI NFS Driver for Kubernetes
    digest: 44406231cd5cdada1c62a0541b93b4f5d5a70ccc8c50b33553a8692fe6cfae96
    name: csi-driver-nfs
    urls:
    - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts/v3.0.0/csi-driver-nfs-v3.0.0.tgz
    version: v3.0.0
  - apiVersion: v1
    appVersion: v2.0.0
    created: "2024-07-18T07:10:05.759849461Z"
    description: CSI NFS Driver for Kubernetes
    digest: 1a32c6fc016526fe19a0c9e0dfbe83d0ddde67ced533bb5f5d24d713f706c613
    name: csi-driver-nfs
    urls:
    - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts/v2.0.0/csi-driver-nfs-v2.0.0.tgz
    version: v2.0.0
  - apiVersion: v1
    appVersion: latest
    created: "2024-07-18T07:10:05.759620108Z"
    description: CSI NFS Driver for Kubernetes
    digest: 82fe0c2e805eacd5c2ec3a514ecbd3655eb582725efe70128272816bafbe685a
    name: csi-driver-nfs
    urls:
    - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts/latest/csi-driver-nfs-v0.0.0.tgz
    version: v0.0.0
generated: "2024-07-18T07:10:05.758679537Z"
