apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csi-driver-nfs
  namespace: kube-system
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: pangarabbit
  source:
    repoURL: "https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts"
    targetRevision: 4.7.0
    chart: csi-driver-nfs
    helm:
      valueFiles:
        - values-dev.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
